# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/IDE/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/IDE/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/andrealeonardo/CLionProjects/CG_PROJECTS/CGproject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/andrealeonardo/CLionProjects/CG_PROJECTS/CGproject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/IDE/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/IDE/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/IDE/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/IDE/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/IDE/CLion.app/Contents/bin/cmake/mac/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/IDE/CLion.app/Contents/bin/cmake/mac/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"assimp-bin\" \"assimp-dev\" \"libassimp5.2.0\" \"libassimp5.2.0-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/IDE/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/IDE/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/andrealeonardo/CLionProjects/CG_PROJECTS/CGproject/CMakeFiles /Users/andrealeonardo/CLionProjects/CG_PROJECTS/CGproject/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/andrealeonardo/CLionProjects/CG_PROJECTS/CGproject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CGproject

# Build rule for target.
CGproject: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CGproject
.PHONY : CGproject

# fast build rule for target.
CGproject/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/build
.PHONY : CGproject/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f assimp/CMakeFiles/uninstall.dir/build.make assimp/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) $(MAKESILENT) -f assimp/code/CMakeFiles/assimp.dir/build.make assimp/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

#=============================================================================
# Target rules for targets named assimp_cmd

# Build rule for target.
assimp_cmd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assimp_cmd
.PHONY : assimp_cmd

# fast build rule for target.
assimp_cmd/fast:
	$(MAKE) $(MAKESILENT) -f assimp/tools/assimp_cmd/CMakeFiles/assimp_cmd.dir/build.make assimp/tools/assimp_cmd/CMakeFiles/assimp_cmd.dir/build
.PHONY : assimp_cmd/fast

#=============================================================================
# Target rules for targets named unit

# Build rule for target.
unit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit
.PHONY : unit

# fast build rule for target.
unit/fast:
	$(MAKE) $(MAKESILENT) -f assimp/test/CMakeFiles/unit.dir/build.make assimp/test/CMakeFiles/unit.dir/build
.PHONY : unit/fast

camera.o: camera.cpp.o

.PHONY : camera.o

# target to build an object file
camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/camera.cpp.o
.PHONY : camera.cpp.o

camera.i: camera.cpp.i

.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s

.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/camera.cpp.s
.PHONY : camera.cpp.s

debug_skinning_technique.o: debug_skinning_technique.cpp.o

.PHONY : debug_skinning_technique.o

# target to build an object file
debug_skinning_technique.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/debug_skinning_technique.cpp.o
.PHONY : debug_skinning_technique.cpp.o

debug_skinning_technique.i: debug_skinning_technique.cpp.i

.PHONY : debug_skinning_technique.i

# target to preprocess a source file
debug_skinning_technique.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/debug_skinning_technique.cpp.i
.PHONY : debug_skinning_technique.cpp.i

debug_skinning_technique.s: debug_skinning_technique.cpp.s

.PHONY : debug_skinning_technique.s

# target to generate assembly for a file
debug_skinning_technique.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/debug_skinning_technique.cpp.s
.PHONY : debug_skinning_technique.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/main.cpp.s
.PHONY : main.cpp.s

math_3d.o: math_3d.cpp.o

.PHONY : math_3d.o

# target to build an object file
math_3d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/math_3d.cpp.o
.PHONY : math_3d.cpp.o

math_3d.i: math_3d.cpp.i

.PHONY : math_3d.i

# target to preprocess a source file
math_3d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/math_3d.cpp.i
.PHONY : math_3d.cpp.i

math_3d.s: math_3d.cpp.s

.PHONY : math_3d.s

# target to generate assembly for a file
math_3d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/math_3d.cpp.s
.PHONY : math_3d.cpp.s

ogldev/ogldev_basic_mesh.o: ogldev/ogldev_basic_mesh.cpp.o

.PHONY : ogldev/ogldev_basic_mesh.o

# target to build an object file
ogldev/ogldev_basic_mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/ogldev/ogldev_basic_mesh.cpp.o
.PHONY : ogldev/ogldev_basic_mesh.cpp.o

ogldev/ogldev_basic_mesh.i: ogldev/ogldev_basic_mesh.cpp.i

.PHONY : ogldev/ogldev_basic_mesh.i

# target to preprocess a source file
ogldev/ogldev_basic_mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/ogldev/ogldev_basic_mesh.cpp.i
.PHONY : ogldev/ogldev_basic_mesh.cpp.i

ogldev/ogldev_basic_mesh.s: ogldev/ogldev_basic_mesh.cpp.s

.PHONY : ogldev/ogldev_basic_mesh.s

# target to generate assembly for a file
ogldev/ogldev_basic_mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/ogldev/ogldev_basic_mesh.cpp.s
.PHONY : ogldev/ogldev_basic_mesh.cpp.s

ogldev/ogldev_texture.o: ogldev/ogldev_texture.cpp.o

.PHONY : ogldev/ogldev_texture.o

# target to build an object file
ogldev/ogldev_texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/ogldev/ogldev_texture.cpp.o
.PHONY : ogldev/ogldev_texture.cpp.o

ogldev/ogldev_texture.i: ogldev/ogldev_texture.cpp.i

.PHONY : ogldev/ogldev_texture.i

# target to preprocess a source file
ogldev/ogldev_texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/ogldev/ogldev_texture.cpp.i
.PHONY : ogldev/ogldev_texture.cpp.i

ogldev/ogldev_texture.s: ogldev/ogldev_texture.cpp.s

.PHONY : ogldev/ogldev_texture.s

# target to generate assembly for a file
ogldev/ogldev_texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/ogldev/ogldev_texture.cpp.s
.PHONY : ogldev/ogldev_texture.cpp.s

ogldev/ogldev_util.o: ogldev/ogldev_util.cpp.o

.PHONY : ogldev/ogldev_util.o

# target to build an object file
ogldev/ogldev_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/ogldev/ogldev_util.cpp.o
.PHONY : ogldev/ogldev_util.cpp.o

ogldev/ogldev_util.i: ogldev/ogldev_util.cpp.i

.PHONY : ogldev/ogldev_util.i

# target to preprocess a source file
ogldev/ogldev_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/ogldev/ogldev_util.cpp.i
.PHONY : ogldev/ogldev_util.cpp.i

ogldev/ogldev_util.s: ogldev/ogldev_util.cpp.s

.PHONY : ogldev/ogldev_util.s

# target to generate assembly for a file
ogldev/ogldev_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/ogldev/ogldev_util.cpp.s
.PHONY : ogldev/ogldev_util.cpp.s

ogldev/ogldev_world_transform.o: ogldev/ogldev_world_transform.cpp.o

.PHONY : ogldev/ogldev_world_transform.o

# target to build an object file
ogldev/ogldev_world_transform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/ogldev/ogldev_world_transform.cpp.o
.PHONY : ogldev/ogldev_world_transform.cpp.o

ogldev/ogldev_world_transform.i: ogldev/ogldev_world_transform.cpp.i

.PHONY : ogldev/ogldev_world_transform.i

# target to preprocess a source file
ogldev/ogldev_world_transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/ogldev/ogldev_world_transform.cpp.i
.PHONY : ogldev/ogldev_world_transform.cpp.i

ogldev/ogldev_world_transform.s: ogldev/ogldev_world_transform.cpp.s

.PHONY : ogldev/ogldev_world_transform.s

# target to generate assembly for a file
ogldev/ogldev_world_transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/ogldev/ogldev_world_transform.cpp.s
.PHONY : ogldev/ogldev_world_transform.cpp.s

skinned_mesh.o: skinned_mesh.cpp.o

.PHONY : skinned_mesh.o

# target to build an object file
skinned_mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/skinned_mesh.cpp.o
.PHONY : skinned_mesh.cpp.o

skinned_mesh.i: skinned_mesh.cpp.i

.PHONY : skinned_mesh.i

# target to preprocess a source file
skinned_mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/skinned_mesh.cpp.i
.PHONY : skinned_mesh.cpp.i

skinned_mesh.s: skinned_mesh.cpp.s

.PHONY : skinned_mesh.s

# target to generate assembly for a file
skinned_mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/skinned_mesh.cpp.s
.PHONY : skinned_mesh.cpp.s

skinning_technique.o: skinning_technique.cpp.o

.PHONY : skinning_technique.o

# target to build an object file
skinning_technique.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/skinning_technique.cpp.o
.PHONY : skinning_technique.cpp.o

skinning_technique.i: skinning_technique.cpp.i

.PHONY : skinning_technique.i

# target to preprocess a source file
skinning_technique.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/skinning_technique.cpp.i
.PHONY : skinning_technique.cpp.i

skinning_technique.s: skinning_technique.cpp.s

.PHONY : skinning_technique.s

# target to generate assembly for a file
skinning_technique.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/skinning_technique.cpp.s
.PHONY : skinning_technique.cpp.s

stb_image.o: stb_image.cpp.o

.PHONY : stb_image.o

# target to build an object file
stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/stb_image.cpp.o
.PHONY : stb_image.cpp.o

stb_image.i: stb_image.cpp.i

.PHONY : stb_image.i

# target to preprocess a source file
stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/stb_image.cpp.i
.PHONY : stb_image.cpp.i

stb_image.s: stb_image.cpp.s

.PHONY : stb_image.s

# target to generate assembly for a file
stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/stb_image.cpp.s
.PHONY : stb_image.cpp.s

technique.o: technique.cpp.o

.PHONY : technique.o

# target to build an object file
technique.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/technique.cpp.o
.PHONY : technique.cpp.o

technique.i: technique.cpp.i

.PHONY : technique.i

# target to preprocess a source file
technique.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/technique.cpp.i
.PHONY : technique.cpp.i

technique.s: technique.cpp.s

.PHONY : technique.s

# target to generate assembly for a file
technique.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGproject.dir/build.make CMakeFiles/CGproject.dir/technique.cpp.s
.PHONY : technique.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... CGproject"
	@echo "... assimp"
	@echo "... assimp_cmd"
	@echo "... unit"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... debug_skinning_technique.o"
	@echo "... debug_skinning_technique.i"
	@echo "... debug_skinning_technique.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... math_3d.o"
	@echo "... math_3d.i"
	@echo "... math_3d.s"
	@echo "... ogldev/ogldev_basic_mesh.o"
	@echo "... ogldev/ogldev_basic_mesh.i"
	@echo "... ogldev/ogldev_basic_mesh.s"
	@echo "... ogldev/ogldev_texture.o"
	@echo "... ogldev/ogldev_texture.i"
	@echo "... ogldev/ogldev_texture.s"
	@echo "... ogldev/ogldev_util.o"
	@echo "... ogldev/ogldev_util.i"
	@echo "... ogldev/ogldev_util.s"
	@echo "... ogldev/ogldev_world_transform.o"
	@echo "... ogldev/ogldev_world_transform.i"
	@echo "... ogldev/ogldev_world_transform.s"
	@echo "... skinned_mesh.o"
	@echo "... skinned_mesh.i"
	@echo "... skinned_mesh.s"
	@echo "... skinning_technique.o"
	@echo "... skinning_technique.i"
	@echo "... skinning_technique.s"
	@echo "... stb_image.o"
	@echo "... stb_image.i"
	@echo "... stb_image.s"
	@echo "... technique.o"
	@echo "... technique.i"
	@echo "... technique.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

